---

- name: Systemd
  when: ansible_service_mgr == 'systemd'
  block:
    - name: Install unit - {{ unit_name }}
      block:
        - name: Install systemd configuration
          ansible.builtin.template:
            src: "systemd-{{ unit_name }}.service.j2"
            dest: "/lib/systemd/system/{{ unit_name }}.service"
            mode: '0644'
            backup: yes
          register: systemdconf
          notify:
            - Reload systemd
            - "Restart {{ unit_name }}"
      rescue:
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system
            state: pre
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: "/lib/systemd/system/{{ unit_name }}.service"
            state: pre
        - name: Install systemd configuration (immutable)
          ansible.builtin.template:
            src: "systemd-{{ unit_name }}.service.j2"
            dest: "/lib/systemd/system/{{ unit_name }}.service"
            mode: '0644'
            backup: yes
          notify:
            - Reload systemd
            - "Restart {{ unit_name }}"
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system
            state: post
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: "/lib/systemd/system/{{ unit_name }}.service"
            state: post
    - name: Service state
      when: falco_service_enabled
      block:
        - name: Enable and start systemd services
          ansible.builtin.service:
            name: "{{ unit_name }}"
            enabled: yes
            state: 'started'
          failed_when: false
    - name: No Service
      when: not falco_service_enabled
      block:
        - name: Disable and stop systemd service
          ansible.builtin.service:
            name: "{{ unit_name }}"
            enabled: no
            state: 'stopped'
          failed_when: false
    - name: Ensure no init.d script
      block:
        - name: Remove init.d script
          ansible.builtin.file:
            path: "/etc/init.d/{{ unit_name }}"
            state: absent
          register: initd
      rescue:
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d/
            state: pre
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: "/etc/init.d/{{ unit_name }}"
            state: pre
        - name: Remove init.d script
          ansible.builtin.file:
            path: "/etc/init.d/{{ unit_name }}"
            state: absent
        - name: Import immutable
          ansible.builtin.import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d
            state: post
